[build]
  publish = "."
  functions = "functions"

# Redirections pour chaque langue
[[redirects]]
  from = "/fr/*"
  to = "/FR/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/es/*"
  to = "/ES/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/de/*"
  to = "/DE/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en/*"
  to = "/EN/index.html"
  status = 200
  force = true

# Headers pour les chemins français
[[headers]]
  for = "/fr/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Headers pour les chemins espagnols
[[headers]]
  for = "/es/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Headers pour les chemins allemands
[[headers]]
  for = "/de/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Headers pour les chemins anglais
[[headers]]
  for = "/en/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
	