[build]
  publish = "."
  functions = "functions"

# Redirections pour la langue française
[[redirects]]
  from = "/fr/*"
  to = "/FR/index.html"
  status = 200
  force = true

# Headers pour les chemins français
[[headers]]
  for = "/FR/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Headers pour les requêtes POST
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
